from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from typing_extensions import TextIO, TYPE_CHECKING

from krrood.code_generation.formatting import run_black_on_file
from krrood.code_generation.generator import CodeGenerator

if TYPE_CHECKING:
    from krrood.ormatic.ormatic import ORMatic

logger = logging.getLogger(__name__)


@dataclass
class SQLAlchemyGenerator:
    """
    A class for generating SQLAlchemy declarative mappings from ORMatic models.
    This class writes the tables generated by ORMatic to a file that serves as
    an SQL database interface.  Uses Jinja2 templates for code generation via
    :class:`~krrood.code_generation.generator.CodeGenerator`.
    """

    ormatic: ORMatic
    """
    The ORMatic instance that created this SQLAlchemyGenerator.
    """

    _generator: CodeGenerator = field(init=False, default=None)

    def __post_init__(self):
        self._generator = CodeGenerator(
            template_dir=os.path.join(
                os.path.dirname(__file__), "..", "jinja_templates"
            ),
        )

    def to_sqlalchemy_file(self, file: TextIO):
        """
        Generate a Python file with SQLAlchemy declarative mappings from the
        ORMatic models.

        :param file: The file to write to
        """
        output = self._generator.render(
            "sqlalchemy_model.py.jinja",
            ormatic=self.ormatic,
        )

        # Write the output to the file
        file.write(output)

        # format the output with black
        run_black_on_file(str(file.name))


