# Generated by ORMatic

from __future__ import annotations
from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    String,
    Float,
    Boolean,
    DateTime,
    Enum,
    JSON,
    Table,
)
from sqlalchemy.orm import relationship, Mapped, mapped_column, DeclarativeBase

import builtins
import coraplex.orm.model
import datetime
import enum
import krrood.adapters.json_serializer
import krrood.ormatic.custom_types
import krrood.ormatic.data_access_objects.alternative_mappings
import krrood.ormatic.type_dict
import numpy
import pathlib
import segmind.datastructures.event_plotter
import segmind.datastructures.events
import segmind.datastructures.object_tracker
import segmind.detectors.atomic_event_detectors_nodes
import segmind.detectors.base
import segmind.detectors.coarse_event_detector_nodes
import segmind.detectors.spatial_relation_detector_nodes
import segmind.episode_player
import segmind.episode_segmenter
import segmind.event_logger
import segmind.players.csv_player
import segmind.players.data_player
import segmind.players.json_player
import segmind.statecharts.segmind_statechart
import segmind.utils
import semantic_digital_twin.orm.model
import semantic_digital_twin.semantic_annotations.semantic_annotations
import semantic_digital_twin.world_description.degree_of_freedom
import semantic_digital_twin.world_description.world_entity
import sqlalchemy.sql.sqltypes
import typing
import typing_extensions
import uuid


from krrood.ormatic.data_access_objects.dao import (
    DataAccessObject,
    AssociationDataAccessObject,
)
from krrood.ormatic.custom_types import TypeType


class Base(DeclarativeBase):
    type_mappings = {
        numpy.ndarray: coraplex.orm.model.NumpyType,
        typing.Type: krrood.ormatic.custom_types.TypeType,
        builtins.type: krrood.ormatic.custom_types.TypeType,
        enum.Enum: krrood.ormatic.custom_types.PolymorphicEnumType,
        krrood.adapters.json_serializer.SubclassJSONSerializer: sqlalchemy.sql.sqltypes.JSON,
        uuid.UUID: sqlalchemy.sql.sqltypes.UUID,
        pathlib.Path: krrood.ormatic.custom_types.PathType,
        krrood.adapters.json_serializer.JSONData: krrood.ormatic.custom_types.JSONDataType,
    }


# Association tables for many-to-many relationships


class PlanMappingDAO(Base, DataAccessObject[coraplex.orm.model.PlanMapping]):
    __tablename__ = "PlanMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    initial_world_id: Mapped[typing.Optional[builtins.int]] = mapped_column(
        ForeignKey("WorldMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    initial_world: Mapped[WorldMappingDAO] = relationship(
        "WorldMappingDAO",
        uselist=False,
        foreign_keys=[initial_world_id],
        post_update=True,
    )


class FunctionMappingDAO(
    Base,
    DataAccessObject[
        krrood.ormatic.data_access_objects.alternative_mappings.FunctionMapping
    ],
):
    __tablename__ = "FunctionMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    module_name: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )
    function_name: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )
    class_name: Mapped[typing.Optional[builtins.str]] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )


class EventPlotterDAO(
    Base, DataAccessObject[segmind.datastructures.event_plotter.EventPlotter]
):
    __tablename__ = "EventPlotterDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class DetectionEventDAO(
    Base, DataAccessObject[segmind.datastructures.events.DetectionEvent]
):
    __tablename__ = "DetectionEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    timestamp: Mapped[datetime.datetime] = mapped_column(use_existing_column=True)

    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "DetectionEventDAO",
    }


class EventWithTrackedObjectsDAO(
    DetectionEventDAO,
    DataAccessObject[segmind.datastructures.events.EventWithTrackedObjects],
):
    __tablename__ = "EventWithTrackedObjectsDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(DetectionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    tracked_object: Mapped[
        semantic_digital_twin.world_description.world_entity.Body
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=False, use_existing_column=True
    )
    with_object: Mapped[
        typing.Optional[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "EventWithTrackedObjectsDAO",
        "inherit_condition": database_id == DetectionEventDAO.database_id,
        "polymorphic_load": "selectin",
    }


class AbstractContactEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.AbstractContactEvent],
):
    __tablename__ = "AbstractContactEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "AbstractContactEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class ContactEventDAO(
    AbstractContactEventDAO,
    DataAccessObject[segmind.datastructures.events.ContactEvent],
):
    __tablename__ = "ContactEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractContactEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "ContactEventDAO",
        "inherit_condition": database_id == AbstractContactEventDAO.database_id,
        "polymorphic_load": "selectin",
    }


class ContainmentEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.ContainmentEvent],
):
    __tablename__ = "ContainmentEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "ContainmentEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class InsertionEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.InsertionEvent],
):
    __tablename__ = "InsertionEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    inserted_into_objects: Mapped[
        typing.List[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)

    __mapper_args__ = {
        "polymorphic_identity": "InsertionEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class LossOfContactEventDAO(
    AbstractContactEventDAO,
    DataAccessObject[segmind.datastructures.events.LossOfContactEvent],
):
    __tablename__ = "LossOfContactEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractContactEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfContactEventDAO",
        "inherit_condition": database_id == AbstractContactEventDAO.database_id,
        "polymorphic_load": "selectin",
    }


class LossOfContainmentEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.LossOfContainmentEvent],
):
    __tablename__ = "LossOfContainmentEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfContainmentEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class LossOfSupportEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.LossOfSupportEvent],
):
    __tablename__ = "LossOfSupportEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfSupportEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class MotionEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.MotionEvent],
):
    __tablename__ = "MotionEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    start_pose_id: Mapped[int] = mapped_column(
        ForeignKey("PoseMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )
    current_pose_id: Mapped[int] = mapped_column(
        ForeignKey("PoseMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    start_pose: Mapped[PoseMappingDAO] = relationship(
        "PoseMappingDAO", uselist=False, foreign_keys=[start_pose_id], post_update=True
    )
    current_pose: Mapped[PoseMappingDAO] = relationship(
        "PoseMappingDAO",
        uselist=False,
        foreign_keys=[current_pose_id],
        post_update=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "MotionEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class PickUpEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.PickUpEvent],
):
    __tablename__ = "PickUpEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "PickUpEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class PlacingEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.PlacingEvent],
):
    __tablename__ = "PlacingEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "PlacingEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class RotationEventDAO(
    MotionEventDAO, DataAccessObject[segmind.datastructures.events.RotationEvent]
):
    __tablename__ = "RotationEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "RotationEventDAO",
        "inherit_condition": database_id == MotionEventDAO.database_id,
        "polymorphic_load": "selectin",
    }


class StopRotationEventDAO(
    MotionEventDAO, DataAccessObject[segmind.datastructures.events.StopRotationEvent]
):
    __tablename__ = "StopRotationEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "StopRotationEventDAO",
        "inherit_condition": database_id == MotionEventDAO.database_id,
        "polymorphic_load": "selectin",
    }


class StopTranslationEventDAO(
    MotionEventDAO, DataAccessObject[segmind.datastructures.events.StopTranslationEvent]
):
    __tablename__ = "StopTranslationEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "StopTranslationEventDAO",
        "inherit_condition": database_id == MotionEventDAO.database_id,
        "polymorphic_load": "selectin",
    }


class SupportEventDAO(
    EventWithTrackedObjectsDAO,
    DataAccessObject[segmind.datastructures.events.SupportEvent],
):
    __tablename__ = "SupportEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EventWithTrackedObjectsDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "SupportEventDAO",
        "inherit_condition": database_id == EventWithTrackedObjectsDAO.database_id,
        "polymorphic_load": "selectin",
    }


class TranslationEventDAO(
    MotionEventDAO, DataAccessObject[segmind.datastructures.events.TranslationEvent]
):
    __tablename__ = "TranslationEventDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionEventDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "TranslationEventDAO",
        "inherit_condition": database_id == MotionEventDAO.database_id,
        "polymorphic_load": "selectin",
    }


class ObjectEventTrackerDAO(
    Base, DataAccessObject[segmind.datastructures.object_tracker.ObjectEventTracker]
):
    __tablename__ = "ObjectEventTrackerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    body: Mapped[
        typing.Optional[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )

    context_id: Mapped[typing.Optional[builtins.int]] = mapped_column(
        ForeignKey("SegmindContextDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    context: Mapped[SegmindContextDAO] = relationship(
        "SegmindContextDAO", uselist=False, foreign_keys=[context_id], post_update=True
    )


class ObjectTrackerFactoryDAO(
    Base, DataAccessObject[segmind.datastructures.object_tracker.ObjectTrackerFactory]
):
    __tablename__ = "ObjectTrackerFactoryDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class AbstractDetectorDAO(
    Base, DataAccessObject[segmind.detectors.base.AbstractDetector]
):
    __tablename__ = "AbstractDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    name: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )

    tracked_object: Mapped[
        typing.Optional[semantic_digital_twin.world_description.world_entity.Body]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )
    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "AbstractDetectorDAO",
    }


class ContactDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[segmind.detectors.atomic_event_detectors_nodes.ContactDetector],
):
    __tablename__ = "ContactDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "ContactDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class LossOfContactDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.atomic_event_detectors_nodes.LossOfContactDetector
    ],
):
    __tablename__ = "LossOfContactDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfContactDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class MotionDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[segmind.detectors.atomic_event_detectors_nodes.MotionDetector],
):
    __tablename__ = "MotionDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    window_size: Mapped[builtins.int] = mapped_column(use_existing_column=True)
    rotation_threshold: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    __mapper_args__ = {
        "polymorphic_identity": "MotionDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class RotationDetectorDAO(
    MotionDetectorDAO,
    DataAccessObject[segmind.detectors.atomic_event_detectors_nodes.RotationDetector],
):
    __tablename__ = "RotationDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "RotationDetectorDAO",
        "inherit_condition": database_id == MotionDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class StopRotationDetectorDAO(
    MotionDetectorDAO,
    DataAccessObject[
        segmind.detectors.atomic_event_detectors_nodes.StopRotationDetector
    ],
):
    __tablename__ = "StopRotationDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "StopRotationDetectorDAO",
        "inherit_condition": database_id == MotionDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class StopTranslationDetectorDAO(
    MotionDetectorDAO,
    DataAccessObject[
        segmind.detectors.atomic_event_detectors_nodes.StopTranslationDetector
    ],
):
    __tablename__ = "StopTranslationDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "StopTranslationDetectorDAO",
        "inherit_condition": database_id == MotionDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class TranslationDetectorDAO(
    MotionDetectorDAO,
    DataAccessObject[
        segmind.detectors.atomic_event_detectors_nodes.TranslationDetector
    ],
):
    __tablename__ = "TranslationDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(MotionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "TranslationDetectorDAO",
        "inherit_condition": database_id == MotionDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class DetectorStateChartDAO(
    Base, DataAccessObject[segmind.detectors.base.DetectorStateChart]
):
    __tablename__ = "DetectorStateChartDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class SegmindContextDAO(Base, DataAccessObject[segmind.detectors.base.SegmindContext]):
    __tablename__ = "SegmindContextDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    holes: Mapped[
        typing.List[
            semantic_digital_twin.semantic_annotations.semantic_annotations.Aperture
        ]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)

    logger_id: Mapped[int] = mapped_column(
        ForeignKey("EventLoggerDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )
    tracker_registry_id: Mapped[int] = mapped_column(
        ForeignKey("ObjectTrackerFactoryDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    logger: Mapped[EventLoggerDAO] = relationship(
        "EventLoggerDAO", uselist=False, foreign_keys=[logger_id], post_update=True
    )
    tracker_registry: Mapped[ObjectTrackerFactoryDAO] = relationship(
        "ObjectTrackerFactoryDAO",
        uselist=False,
        foreign_keys=[tracker_registry_id],
        post_update=True,
    )


class AbstractInteractionDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.coarse_event_detector_nodes.AbstractInteractionDetector
    ],
):
    __tablename__ = "AbstractInteractionDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "AbstractInteractionDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class PickUpDetectorDAO(
    AbstractInteractionDetectorDAO,
    DataAccessObject[segmind.detectors.coarse_event_detector_nodes.PickUpDetector],
):
    __tablename__ = "PickUpDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractInteractionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "PickUpDetectorDAO",
        "inherit_condition": database_id == AbstractInteractionDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class PlacingDetectorDAO(
    AbstractInteractionDetectorDAO,
    DataAccessObject[segmind.detectors.coarse_event_detector_nodes.PlacingDetector],
):
    __tablename__ = "PlacingDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractInteractionDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "PlacingDetectorDAO",
        "inherit_condition": database_id == AbstractInteractionDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class BaseContainmentDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.BaseContainmentDetector
    ],
):
    __tablename__ = "BaseContainmentDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    containment_threshold: Mapped[builtins.float] = mapped_column(
        use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "BaseContainmentDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class ContainmentDetectorDAO(
    BaseContainmentDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.ContainmentDetector
    ],
):
    __tablename__ = "ContainmentDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(BaseContainmentDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "ContainmentDetectorDAO",
        "inherit_condition": database_id == BaseContainmentDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class InsertionDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.InsertionDetector
    ],
):
    __tablename__ = "InsertionDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "InsertionDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class LossOfContainmentDetectorDAO(
    BaseContainmentDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.LossOfContainmentDetector
    ],
):
    __tablename__ = "LossOfContainmentDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(BaseContainmentDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfContainmentDetectorDAO",
        "inherit_condition": database_id == BaseContainmentDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class LossOfSupportDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[
        segmind.detectors.spatial_relation_detector_nodes.LossOfSupportDetector
    ],
):
    __tablename__ = "LossOfSupportDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "LossOfSupportDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class SupportDetectorDAO(
    AbstractDetectorDAO,
    DataAccessObject[segmind.detectors.spatial_relation_detector_nodes.SupportDetector],
):
    __tablename__ = "SupportDetectorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(AbstractDetectorDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "SupportDetectorDAO",
        "inherit_condition": database_id == AbstractDetectorDAO.database_id,
        "polymorphic_load": "selectin",
    }


class EpisodeSegmenterExecutorDAO(
    Base, DataAccessObject[segmind.episode_segmenter.EpisodeSegmenterExecutor]
):
    __tablename__ = "EpisodeSegmenterExecutorDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    tmp_folder: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )


class EventLoggerDAO(Base, DataAccessObject[segmind.event_logger.EventLogger]):
    __tablename__ = "EventLoggerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    annotate_events: Mapped[builtins.bool] = mapped_column(use_existing_column=True)


class FrameDataDAO(Base, DataAccessObject[segmind.players.data_player.FrameData]):
    __tablename__ = "FrameDataDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    time: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    frame_idx: Mapped[builtins.int] = mapped_column(use_existing_column=True)


class SegmindStatechartDAO(
    Base, DataAccessObject[segmind.statecharts.segmind_statechart.SegmindStatechart]
):
    __tablename__ = "SegmindStatechartDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )


class PropagatingThreadDAO(Base, DataAccessObject[segmind.utils.PropagatingThread]):
    __tablename__ = "PropagatingThreadDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "PropagatingThreadDAO",
    }


class EpisodePlayerDAO(
    PropagatingThreadDAO, DataAccessObject[segmind.episode_player.EpisodePlayer]
):
    __tablename__ = "EpisodePlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(PropagatingThreadDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    use_realtime: Mapped[builtins.bool] = mapped_column(use_existing_column=True)
    stop_after_ready: Mapped[builtins.bool] = mapped_column(use_existing_column=True)
    rdr_viewer: Mapped[builtins.NoneType] = mapped_column(use_existing_column=True)

    world_id: Mapped[typing.Optional[builtins.int]] = mapped_column(
        ForeignKey("WorldMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    world: Mapped[WorldMappingDAO] = relationship(
        "WorldMappingDAO", uselist=False, foreign_keys=[world_id], post_update=True
    )

    __mapper_args__ = {
        "polymorphic_identity": "EpisodePlayerDAO",
        "inherit_condition": database_id == PropagatingThreadDAO.database_id,
        "polymorphic_load": "selectin",
    }


class DataPlayerDAO(
    EpisodePlayerDAO, DataAccessObject[segmind.players.data_player.DataPlayer]
):
    __tablename__ = "DataPlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(EpisodePlayerDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    sync_robot_only: Mapped[builtins.bool] = mapped_column(use_existing_column=True)

    __mapper_args__ = {
        "polymorphic_identity": "DataPlayerDAO",
        "inherit_condition": database_id == EpisodePlayerDAO.database_id,
        "polymorphic_load": "selectin",
    }


class FilePlayerDAO(
    DataPlayerDAO, DataAccessObject[segmind.players.data_player.FilePlayer]
):
    __tablename__ = "FilePlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(DataPlayerDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    file_path: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )
    models_dir: Mapped[typing.Optional[builtins.str]] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )

    position_shift_id: Mapped[typing.Optional[builtins.int]] = mapped_column(
        ForeignKey("Vector3MappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    position_shift: Mapped[Vector3MappingDAO] = relationship(
        "Vector3MappingDAO",
        uselist=False,
        foreign_keys=[position_shift_id],
        post_update=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "FilePlayerDAO",
        "inherit_condition": database_id == DataPlayerDAO.database_id,
        "polymorphic_load": "selectin",
    }


class CSVEpisodePlayerDAO(
    FilePlayerDAO, DataAccessObject[segmind.players.csv_player.CSVEpisodePlayer]
):
    __tablename__ = "CSVEpisodePlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(FilePlayerDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "CSVEpisodePlayerDAO",
        "inherit_condition": database_id == FilePlayerDAO.database_id,
        "polymorphic_load": "selectin",
    }


class JSONPlayerDAO(
    FilePlayerDAO, DataAccessObject[segmind.players.json_player.JSONPlayer]
):
    __tablename__ = "JSONPlayerDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(FilePlayerDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    scene_id: Mapped[builtins.int] = mapped_column(use_existing_column=True)
    mesh_scale: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    __mapper_args__ = {
        "polymorphic_identity": "JSONPlayerDAO",
        "inherit_condition": database_id == FilePlayerDAO.database_id,
        "polymorphic_load": "selectin",
    }


class HomogeneousTransformationMatrixMappingDAO(
    Base,
    DataAccessObject[
        semantic_digital_twin.orm.model.HomogeneousTransformationMatrixMapping
    ],
):
    __tablename__ = "HomogeneousTransformationMatrixMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )
    child_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )

    position_id: Mapped[int] = mapped_column(
        ForeignKey("Point3MappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )
    rotation_id: Mapped[int] = mapped_column(
        ForeignKey("QuaternionMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    position: Mapped[Point3MappingDAO] = relationship(
        "Point3MappingDAO", uselist=False, foreign_keys=[position_id], post_update=True
    )
    rotation: Mapped[QuaternionMappingDAO] = relationship(
        "QuaternionMappingDAO",
        uselist=False,
        foreign_keys=[rotation_id],
        post_update=True,
    )


class Point3MappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.Point3Mapping]
):
    __tablename__ = "Point3MappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    x: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    y: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    z: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )


class PoseMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.PoseMapping]
):
    __tablename__ = "PoseMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )
    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    position_id: Mapped[int] = mapped_column(
        ForeignKey("Point3MappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )
    orientation_id: Mapped[int] = mapped_column(
        ForeignKey("QuaternionMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    position: Mapped[Point3MappingDAO] = relationship(
        "Point3MappingDAO", uselist=False, foreign_keys=[position_id], post_update=True
    )
    orientation: Mapped[QuaternionMappingDAO] = relationship(
        "QuaternionMappingDAO",
        uselist=False,
        foreign_keys=[orientation_id],
        post_update=True,
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "PoseMappingDAO",
    }


class GrasPoseMappingDAO(
    PoseMappingDAO, DataAccessObject[coraplex.orm.model.GrasPoseMapping]
):
    __tablename__ = "GrasPoseMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(PoseMappingDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    arm: Mapped[typing.Optional[coraplex.datastructures.enums.Arms]] = mapped_column(
        krrood.ormatic.custom_types.PolymorphicEnumType,
        nullable=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "GrasPoseMappingDAO",
        "inherit_condition": database_id == PoseMappingDAO.database_id,
        "polymorphic_load": "selectin",
    }


class Pose2DMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.Pose2DMapping]
):
    __tablename__ = "Pose2DMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    x: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    y: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    yaw: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )


class QuaternionMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.QuaternionMapping]
):
    __tablename__ = "QuaternionMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    x: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    y: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    z: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    w: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )


class RotationMatrixMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.RotationMatrixMapping]
):
    __tablename__ = "RotationMatrixMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )

    rotation_id: Mapped[int] = mapped_column(
        ForeignKey("QuaternionMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    rotation: Mapped[QuaternionMappingDAO] = relationship(
        "QuaternionMappingDAO",
        uselist=False,
        foreign_keys=[rotation_id],
        post_update=True,
    )


class Vector3MappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.Vector3Mapping]
):
    __tablename__ = "Vector3MappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    x: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    y: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    z: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )


class WorldMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.WorldMapping]
):
    __tablename__ = "WorldMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    name: Mapped[typing.Optional[builtins.str]] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )

    kinematic_structure_entities: Mapped[
        typing.List[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)
    connections: Mapped[
        typing.List[semantic_digital_twin.world_description.world_entity.Connection]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)
    semantic_annotations: Mapped[
        typing.List[
            semantic_digital_twin.world_description.world_entity.SemanticAnnotation
        ]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)
    degrees_of_freedom: Mapped[
        typing.List[
            semantic_digital_twin.world_description.degree_of_freedom.DegreeOfFreedom
        ]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)

    state_id: Mapped[int] = mapped_column(
        ForeignKey("WorldStateMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    state: Mapped[WorldStateMappingDAO] = relationship(
        "WorldStateMappingDAO", uselist=False, foreign_keys=[state_id], post_update=True
    )


class WorldStateMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.WorldStateMapping]
):
    __tablename__ = "WorldStateMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    data: Mapped[typing.List[builtins.float]] = mapped_column(
        JSON, nullable=False, use_existing_column=True
    )
    ids: Mapped[typing.List[uuid.UUID]] = mapped_column(
        JSON, nullable=False, use_existing_column=True
    )
