from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Iterable, Optional, Self, Tuple, TYPE_CHECKING, Union

import numpy as np
from typing_extensions import List

from krrood.ormatic.utils import classproperty
from krrood.symbolic_math import symbolic_math
from random_events.interval import closed
from random_events.product_algebra import SimpleEvent
from semantic_digital_twin.datastructures.alignment import AlignmentPair
from semantic_digital_twin.datastructures.prefixed_name import PrefixedName
from semantic_digital_twin.datastructures.variables import SpatialVariables
from semantic_digital_twin.exceptions import (
    InvalidPlaneDimensions,
    InvalidHingeActiveAxis,
    MissingSemanticAnnotationError,
    MechanicalJointAlreadyMounted,
)
from semantic_digital_twin.reasoning.predicates import InsideOf
from semantic_digital_twin.semantic_annotations.part_whole import (
    IsPartWholeRelationship,
)
from semantic_digital_twin.semantic_annotations.mixins import (
    HasSupportingSurface,
    HasRootRegion,
    HasDrawers,
    HasDoors,
    HasHandle,
    HasCaseAsRootBody,
    HasMechanicalJoint,
    HasApertures,
    IsPerceivable,
    HasRootBody,
    IsStorageSpace,
    HasLegs,
    HasSink,
    HasShelfLayers,
)
from semantic_digital_twin.spatial_types import (
    Point3,
    HomogeneousTransformationMatrix,
    Vector3,
)
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world_description.connections import (
    FixedConnection,
)
from semantic_digital_twin.world_description.degree_of_freedom import (
    DegreeOfFreedomLimits,
)
from semantic_digital_twin.world_description.geometry import (
    VolumetricBoundingBox,
    Scale,
    Color,
)
from semantic_digital_twin.world_description.shape_collection import (
    BoundingBoxCollection,
)
from semantic_digital_twin.world_description.world_entity import (
    SemanticAnnotation,
    Body,
)
from semantic_digital_twin.api import (
    BodySpecification,
    ConnectionSpecification,
    KinematicStructureEntitySpecification,
    PrismaticConnectionSpecification,
    RegionSpecification,
    RevoluteConnectionSpecification,
    ScrewConnectionSpecification,
    SemanticAnnotationWithRootSpecification,
)

if TYPE_CHECKING:
    from semantic_digital_twin.world import World


@dataclass(eq=False)
class Furniture(SemanticAnnotation, ABC):
    """
    A semantic annotation that represents a piece of furniture.
    """


@dataclass(eq=False)
class Handle(HasRootBody):
    """
    A handle is a physical entity that can be grasped by a hand or a robotic gripper to
    open or close an object.
    """

    @classmethod
    def _create_handle_geometry(
        cls, scale: Scale, thickness: float = 0.0
    ) -> SimpleEvent:
        """
        Create a box event representing the handle.

        :param scale: The scale of the handle.
        :param thickness: The thickness of the handle walls.
        """
        x_interval = closed(-scale.x + thickness, 0)
        y_interval = closed(-scale.y / 2, scale.y / 2)
        z_interval = closed(
            -scale.z / 2 + thickness,
            scale.z / 2 - thickness,
        )

        return SimpleEvent.from_data(
            {
                SpatialVariables.x.value: x_interval,
                SpatialVariables.y.value: y_interval,
                SpatialVariables.z.value: z_interval,
            }
        )

    @classmethod
    def get_default_root_kinematic_structure_entity_specification(
        cls,
        name: Optional[str] = None,
        scale: Optional[Scale] = None,
        connection_specification: Optional[ConnectionSpecification] = None,
        *,
        thickness: float = 0.005,
    ) -> BodySpecification:
        """
        Build the default handle body specification, matching the hollow handle geometry
        generated by :meth:`create_with_new_body_in_world`.

        :param name: The name of bodies created from the specification.
        :param scale: The scale of the handle. Defaults to ``Scale(0.05, 0.02, 0.1)``.
        :param thickness: The thickness of the handle walls.
        :param connection_specification: Connection attaching the entity to its parent.
            ``None`` defers to the annotation type's default at spawn time.
        :return: A body specification with the handle geometry.
        """
        scale = scale or Scale(0.05, 0.02, 0.1)
        handle_event = cls._create_handle_geometry(scale=scale).as_composite_set()
        inner_box = cls._create_handle_geometry(
            scale=scale, thickness=thickness
        ).as_composite_set()
        handle_event -= inner_box

        return BodySpecification.from_event(
            name, handle_event, connection_specification=connection_specification
        )


@dataclass(eq=False)
class Dishwasher(HasCaseAsRootBody, HasDoors, HasDrawers):
    """
    A dishwasher is a kitchen appliance used for cleaning dishes, utensils, and
    cookware.

    It typically has a front door that opens to reveal racks for loading dirty items and
    a control panel for selecting wash cycles.
    """

    @classproperty
    def hole_direction(self) -> Vector3:
        return Vector3.NEGATIVE_X()


@dataclass(eq=False)
class Aperture(HasRootRegion):
    """
    An opening in a physical entity.

    An example is like a hole in a wall that can be used to enter a room.
    """

    @classmethod
    def create_with_new_region_in_world_from_body(
        cls,
        name: str,
        world: World,
        body: Body,
        parent_T_self: Optional[HomogeneousTransformationMatrix] = None,
    ) -> Self:
        world.update_forward_kinematics()
        body_scale = (
            body.collision.as_bounding_box_collection_in_frame(body)
            .bounding_box()
            .scale
        )
        return cls.create_with_new_region_in_world(
            name, world, parent_T_self, scale=body_scale
        )

    def _mount_strategy(
        self,
        main_has_root_body_annotation: HasRootBody,
        relationship: IsPartWholeRelationship,
    ) -> None:
        """
        Cut this aperture out of the whole's geometry when the relationship calls for
        it, then mount as a kinematic child.

        An aperture mounted into a field that does not remove geometry marks a passage
        rather than a hole, so the whole keeps its material.
        """
        if relationship.removes_part_geometry_from_whole:
            self._remove_aperture_geometry_from_parent(main_has_root_body_annotation)
        super()._mount_strategy(main_has_root_body_annotation, relationship)

    def _remove_aperture_geometry_from_parent(self, parent: HasRootBody):
        """
        Remove the geometry of the aperture from the parent body's collision and visual
        geometry.

        :param parent: The parent from which the aperture geometry is removed.
        """
        world = parent._world
        world.update_forward_kinematics()
        hole_event = self.root.area.as_bounding_box_collection_in_frame(
            parent.root
        ).event
        wall_event = parent.root.collision.as_bounding_box_collection_in_frame(
            parent.root
        ).event
        new_wall_event = wall_event - hole_event
        new_bounding_box_collection = BoundingBoxCollection.from_event(
            VolumetricBoundingBox, parent.root, new_wall_event
        ).as_shapes()

        parent.root.collision = new_bounding_box_collection
        parent.root.visual = new_bounding_box_collection

    @classmethod
    def get_default_root_kinematic_structure_entity_specification(
        cls,
        name: Optional[str] = None,
        scale: Optional[Scale] = None,
        connection_specification: Optional[ConnectionSpecification] = None,
    ) -> RegionSpecification:
        """
        Build the default region specification whose ``area`` geometry matches what
        :meth:`create_with_new_region_in_world` generates from ``scale``.

        :param name: The name of regions created from the specification.
        :param scale: The scale used to generate the region area geometry. Defaults to
            ``Scale()``.
        :param connection_specification: Connection attaching the entity to its parent.
            ``None`` defers to the annotation type's default at spawn time.
        :return: A region specification with a single box area derived from ``scale``.
        """
        scale = scale or Scale()
        return RegionSpecification.from_event(
            name,
            scale.to_simple_event().as_composite_set(),
            connection_specification=connection_specification,
        )


@dataclass(eq=False)
class MechanicalJoint(HasRootBody):
    """
    A mechanical joint is a physical entity that connects two bodies and allows one to
    move along or around a fixed axis.
    """

    def _mount_strategy(
        self,
        main_has_root_body_annotation: HasRootBody,
        relationship: IsPartWholeRelationship,
    ) -> None:
        """
        Inserts the joint between the whole (``main_has_root_body_annotation``) and the
        whole's current parent, preserving the whole's ancestry.

        Ordinarily, whole_parent -(fixed)-> whole becomes whole_parent -(active)->
        joint -(fixed)-> whole: the joint keeps its own active connection (now
        anchored at the whole's parent), and the whole hangs rigidly off the joint.

        When the whole is already wired straight to its parent through a connection
        of the same type this joint provides (for example a door whose URDF attaches
        it to its cabinet with a revolute joint directly, without a hinge body in
        between), that connection is redundant with the joint's own: the joint takes
        over carrying the physical joint data (its creator is expected to have copied
        the axis, limits, ... over from it), the whole's old connection to its parent
        is discarded, and the whole is attached to the joint with a fixed connection
        instead. The degree of freedom the discarded connection used is reclaimed by
        :meth:`World.delete_orphaned_dofs` when the enclosing ``modify_world`` block
        exits.
        """
        if (
            main_has_root_body_annotation.root.parent_kinematic_structure_entity
            == self.root
        ):
            return
        # used instead of World.compute_child_kinematic_structure_entities because its memoized
        if list(self._world.kinematic_structure.successors(self.root.index)):
            raise MechanicalJointAlreadyMounted(self, main_has_root_body_annotation)

        whole_parent = (
            main_has_root_body_annotation.root.parent_kinematic_structure_entity
        )
        whole_already_carries_this_joint_type = type(
            main_has_root_body_annotation.root.parent_connection
        ) is type(self.root.parent_connection)

        # Mounting always runs inside a still-open modification block, so take the
        # offline path, like every other mount strategy does.
        self._world.move_branch(
            self.root, whole_parent, enable_unsafe_inside_world_block=True
        )

        if whole_already_carries_this_joint_type:
            main_has_root_body_annotation._world.move_branch_with_fixed_connection(
                main_has_root_body_annotation.root,
                self.root,
                enable_unsafe_inside_world_block=True,
            )
        else:
            main_has_root_body_annotation._world.move_branch(
                main_has_root_body_annotation.root,
                self.root,
                enable_unsafe_inside_world_block=True,
            )

    @property
    def position(self):
        return self.root.parent_connection.position

    @position.setter
    def position(self, value):
        self.root.parent_connection.position = value


@dataclass(eq=False)
class Hinge(MechanicalJoint):
    """
    A hinge is a physical entity that connects two bodies and allows one to rotate
    around a fixed axis.
    """

    @classmethod
    def parent_connection_specification(
        cls,
        axis: Optional[Vector3] = None,
        multiplier: float = 1.0,
        offset: float = 0.0,
        dof_limits: Optional[DegreeOfFreedomLimits] = None,
    ) -> RevoluteConnectionSpecification:
        """
        Build the revolute connection a hinge rotates about.

        :param axis: Rotation axis. Defaults to the z axis.
        :param multiplier: Scaling factor applied to the degree of freedom's motion.
        :param offset: Constant offset applied to the degree of freedom's motion.
        :param dof_limits: Limits for the generated degree of freedom.
        :return: The revolute connection specification.
        """
        return RevoluteConnectionSpecification(
            axis=axis if axis is not None else Vector3.Z(),
            multiplier=multiplier,
            offset=offset,
            dof_limits=dof_limits,
        )


@dataclass(eq=False)
class Slider(MechanicalJoint):
    """
    A Slider is a physical entity that connects two bodies and allows one to linearly
    translate along a fixed axis.
    """

    @classmethod
    def parent_connection_specification(
        cls,
        axis: Optional[Vector3] = None,
        multiplier: float = 1.0,
        offset: float = 0.0,
        dof_limits: Optional[DegreeOfFreedomLimits] = None,
    ) -> PrismaticConnectionSpecification:
        """
        Build the prismatic connection a slider translates along.

        :param axis: Translation axis. Defaults to the z axis.
        :param multiplier: Scaling factor applied to the degree of freedom's motion.
        :param offset: Constant offset applied to the degree of freedom's motion.
        :param dof_limits: Limits for the generated degree of freedom.
        :return: The prismatic connection specification.
        """
        return PrismaticConnectionSpecification(
            axis=axis if axis is not None else Vector3.Z(),
            multiplier=multiplier,
            offset=offset,
            dof_limits=dof_limits,
        )


@dataclass(eq=False)
class ScrewMechanism(MechanicalJoint):
    """
    A screw joint is a physical entity that connects two bodies and couples rotation
    about a fixed axis with translation along that axis into a single degree of freedom,
    like the thread between a bottle and its cap.
    """

    @classmethod
    def parent_connection_specification(
        cls,
        axis: Optional[Vector3] = None,
        multiplier: float = 1.0,
        offset: float = 0.0,
        dof_limits: Optional[DegreeOfFreedomLimits] = None,
        screw_pitch: float = 0.001,
    ) -> ScrewConnectionSpecification:
        """
        Build the screw connection a screw mechanism moves along.

        :param axis: Thread axis. Defaults to the z axis.
        :param multiplier: Scaling factor applied to the degree of freedom's motion.
        :param offset: Constant offset applied to the degree of freedom's motion.
        :param dof_limits: Limits for the generated degree of freedom.
        :param screw_pitch: The distance between adjacent threads along ``axis`` in
            meters.
        :return: The screw connection specification.
        """
        return ScrewConnectionSpecification(
            axis=axis if axis is not None else Vector3.Z(),
            multiplier=multiplier,
            offset=offset,
            dof_limits=dof_limits,
            screw_pitch=screw_pitch,
        )

    @property
    def screw_pitch(self) -> float:
        """
        The distance between adjacent threads along the thread axis in meters, read from
        the screw connection this mechanism moves along.
        """
        return self.root.parent_connection.screw_pitch


@dataclass(eq=False)
class EntryWay(Aperture):
    """
    The passage a door covers.

    It is coextensive with the door leaf, so mounting it on its door leaves the door's
    geometry intact; mounting it on a :class:`Wall` cuts the doorway out of the wall.
    """

    @classmethod
    def get_default_root_kinematic_structure_entity_specification(
        cls,
        name: Optional[str] = None,
        scale: Optional[Scale] = None,
        connection_specification: Optional[ConnectionSpecification] = None,
        *,
        color: Optional[Color] = None,
    ) -> RegionSpecification:
        """
        Build the default entry way region specification: a box coextensive with the
        door leaf, translucent so the passage is visible without occluding the door.

        :param name: The name of regions created from the specification.
        :param scale: The scale of the passage. Defaults to ``Scale()``.
        :param connection_specification: Connection attaching the entity to its parent.
            ``None`` defers to the annotation type's default at spawn time.
        :param color: The colour of the passage. Defaults to translucent white.
        :return: A region specification with the passage geometry.
        """
        return RegionSpecification.box(
            name,
            scale or Scale(),
            color=color or Color(R=1.0, G=1.0, B=1.0, A=0.2),
            connection_specification=connection_specification,
        )


@dataclass(eq=False)
class Door(HasHandle, HasMechanicalJoint):
    """
    A door is a physical entity that has covers an opening, has a movable body and a
    handle.
    """

    entry_way: Optional[EntryWay] = field(
        default=None, metadata=IsPartWholeRelationship().as_dict()
    )
    """
    The entry way of the door: the passage the door covers.

    It is coextensive with the door leaf, so mounting it leaves the door's geometry
    intact; mounting the same entry way on a :class:`Wall` cuts the doorway out of it.
    """

    @classproperty
    def default_scale(cls) -> Scale:
        """
        The scale the door's geometry and its entry way are built from when the caller
        supplies none.
        """
        return Scale(0.03, 1, 2)

    @classmethod
    def get_annotation_specification(
        cls,
        name: str,
        root_specification: KinematicStructureEntitySpecification,
        *,
        parent_connection_specification: Optional[ConnectionSpecification] = None,
        annotation_kwargs: Optional[dict] = None,
        part_specifications: Optional[dict] = None,
    ) -> SemanticAnnotationWithRootSpecification[Self]:
        """
        Extend the door specification with its entry way, declared as a nested part so a
        door always carries the passage it covers.

        The entry way is coextensive with the door leaf, so it is sized from the root
        specification's own geometry rather than from a separately supplied scale. A
        caller-supplied ``entry_way`` entry replaces the default one.

        :param name: The name of the annotation and its root entity.
        :param root_specification: The specification of the door's root body.
        :param parent_connection_specification: Connection attaching the root to its
            parent.
        :param annotation_kwargs: Inert keyword arguments for the annotation
            constructor.
        :param part_specifications: Nested annotation parts keyed by part-whole
            relationship field name.
        :return: The annotation specification.
        """
        entry_way_specification = EntryWay.get_annotation_specification(
            f"{name}_entry_way",
            EntryWay.get_default_root_kinematic_structure_entity_specification(
                scale=root_specification.scale
            ),
        )
        return super().get_annotation_specification(
            name,
            root_specification,
            parent_connection_specification=parent_connection_specification,
            annotation_kwargs=annotation_kwargs,
            part_specifications={
                "entry_way": entry_way_specification,
                **(part_specifications if part_specifications is not None else {}),
            },
        )

    @classmethod
    def get_default_root_kinematic_structure_entity_specification(
        cls,
        name: Optional[str] = None,
        scale: Optional[Scale] = None,
        connection_specification: Optional[ConnectionSpecification] = None,
    ) -> BodySpecification:
        """
        Build the default door body specification.

        The door geometry is the base solid box; the ``EntryWay`` is a nested part
        specification and is not part of the door's own geometry.

        :param name: The name of bodies created from the specification.
        :param scale: The scale of the door. ``scale.x`` must be the smallest dimension.
            Defaults to :attr:`default_scale`.
        :param connection_specification: Connection attaching the entity to its parent.
            ``None`` defers to the annotation type's default at spawn time.
        :return: A body specification with the door box geometry.
        """
        scale = scale or cls.default_scale
        if not (scale.x < scale.y and scale.x < scale.z):
            raise InvalidPlaneDimensions(scale, clazz=Door)
        return super().get_default_root_kinematic_structure_entity_specification(
            name, scale, connection_specification
        )

    def calculate_world_T_hinge_based_on_handle(
        self, opening_axis: Vector3
    ) -> HomogeneousTransformationMatrix:
        """
        Calculate the door pivot point based on the handle position and the door scale.

        The pivot point is on the opposite side of the handle.
        :return: The transformation matrix defining the door's pivot point.
        """
        if self.handle is None:
            raise MissingSemanticAnnotationError(self.__class__, Handle)

        connection = self.handle.root.parent_connection
        door_P_handle = connection.origin_expression.to_position()
        scale = self.root.collision.scale
        world_T_door = self.root.global_transform

        match opening_axis.to_np().tolist():
            case [0, 1, 0, 0]:
                sign = (
                    symbolic_math.sign(-1 * door_P_handle.z)
                    if door_P_handle.z != 0
                    else 1
                )
                offset = sign * (scale.z / 2)
                door_T_hinge = HomogeneousTransformationMatrix.from_xyz_rpy(z=offset)

            case [0, 0, 1, 0]:
                sign = (
                    symbolic_math.sign(-1 * door_P_handle.y)
                    if door_P_handle.y != 0
                    else 1
                )
                offset = sign * (scale.y / 2)
                door_T_hinge = HomogeneousTransformationMatrix.from_xyz_rpy(y=offset)
            case [1, 0, 0, 0]:
                sign = (
                    symbolic_math.sign(-1 * door_P_handle.x)
                    if door_P_handle.x != 0
                    else 1
                )
                offset = sign * (scale.x / 2)
                door_T_hinge = HomogeneousTransformationMatrix.from_xyz_rpy(x=offset)

            case _:
                raise InvalidHingeActiveAxis(axis=opening_axis)

        world_T_hinge = world_T_door @ door_T_hinge

        return world_T_hinge


@dataclass(eq=False)
class DoubleDoor(SemanticAnnotation):
    """
    A semantic annotation that represents a double door with left and right doors.
    """

    door_0: Door = field(kw_only=True)
    door_1: Door = field(kw_only=True)

    def calculate_left_right_door_from_view_point(
        self, world_T_view_point: HomogeneousTransformationMatrix
    ) -> Tuple[Door, Door]:
        """
        Calculate which door is the left and which is the right door based on a given
        view point.

        :param world_T_view_point: The transformation matrix of the view point.
        :return: A tuple containing the left and right door. the first door is the left
            door, the second door is the right door.
        """
        world_T_door_0 = self.door_0.root.global_transform
        view_point_T_door_0 = world_T_view_point.inverse() @ world_T_door_0
        world_T_door_1 = self.door_1.root.global_transform
        view_point_T_door_1 = world_T_view_point.inverse() @ world_T_door_1
        if view_point_T_door_0.y > view_point_T_door_1.y:
            return self.door_0, self.door_1
        else:
            return self.door_1, self.door_0


@dataclass(eq=False)
class Drawer(Furniture, HasCaseAsRootBody, HasHandle, HasMechanicalJoint):
    @classproperty
    def hole_direction(self) -> Vector3:
        return Vector3.Z()


@dataclass(eq=False)
class Elevator(HasCaseAsRootBody, HasDoors, HasMechanicalJoint):
    """
    An elevator in the world, consists of three walls a floor, double doors for entering and a prismatic drive that moves
    the elevator to other floors.
    """

    @classproperty
    def hole_direction(self) -> Vector3:
        return Vector3.NEGATIVE_X()

    def open(self):
        """
        Opens the elevator doors
        """
        for door in self.doors:
            door.mechanical_joint.position = (
                door.mechanical_joint.root.parent_connection.dof.limits.upper.position
            )

    def close(self):
        """
        Closes the elevator doors
        """
        for door in self.doors:
            door.mechanical_joint.position = door.mechanical_joint.position = (
                door.mechanical_joint.root.parent_connection.dof.limits.lower.position
            )

    def drive_to_floor(self, floor: Level):
        """
        Drives the elevator to the floor given
        """
        drive_height = floor.floor_plane[0].z + (self.scale.z / 2)
        self.mechanical_joint.position = drive_height


############################### subclasses to Furniture


@dataclass(eq=False)
class ShelfLayer(HasSupportingSurface):
    """
    A horizontal surface used for storing objects, typically found inside cabinets or on
    walls.
    """


@dataclass(eq=False)
class Table(Furniture, HasSupportingSurface):
    """
    A semantic annotation that represents a table.
    """


@dataclass(eq=False)
class CounterTop(Furniture, HasSupportingSurface, HasSink):
    """
    A semantic annotation that represents a counter top.
    """


@dataclass(eq=False)
class Cabinet(Furniture, HasCaseAsRootBody, HasDoors, HasDrawers):
    @classproperty
    def hole_direction(self) -> Vector3:
        return Vector3.NEGATIVE_X()


@dataclass(eq=False)
class Fridge(Cabinet): ...


@dataclass(eq=False)
class Oven(HasRootBody, HasDoors): ...


@dataclass(eq=False)
class Dresser(Cabinet): ...


@dataclass(eq=False)
class Cupboard(Cabinet): ...


@dataclass(eq=False)
class Wardrobe(Cabinet): ...


@dataclass(eq=False)
class Floor(HasSupportingSurface):
    @classmethod
    def create_with_new_body_from_polytope_in_world(
        cls,
        name: str,
        world: World,
        floor_polytope: List[Point3],
        world_root_T_self: Optional[HomogeneousTransformationMatrix] = None,
    ) -> Self:
        """
        Create a Floor semantic annotation with a new body defined by the given list of
        Point3.

        :param name: The name of the floor body.
        :param floor_polytope: A list of 3D points defining the floor poly
        """
        return cls.get_annotation_specification(
            name,
            BodySpecification.from_3d_points(name, floor_polytope),
        ).spawn(world, parent_T_self=world_root_T_self)

    @classmethod
    def get_default_root_kinematic_structure_entity_specification(
        cls,
        name: Optional[str] = None,
        scale: Optional[Scale] = None,
        connection_specification: Optional[ConnectionSpecification] = None,
    ) -> BodySpecification:
        """
        Build the default floor body specification, matching the convex-hull polytope
        geometry generated by :meth:`create_with_new_body_in_world` (which derives
        points from the scale bounding box).

        :param name: The name of bodies created from the specification.
        :param scale: The scale defining the floor polytope. Defaults to ``Scale()``.
        :param connection_specification: Connection attaching the entity to its parent.
            ``None`` defers to the annotation type's default at spawn time.
        :return: A body specification with the floor polytope mesh.
        """
        scale = scale or Scale()
        return BodySpecification.from_3d_points(
            name,
            scale.to_bounding_box().get_points(),
            connection_specification=connection_specification,
        )


@dataclass(eq=False)
class Room(SemanticAnnotation):
    """
    A closed area with a specific purpose.
    """

    floor: Floor = field(kw_only=True)
    """
    The room's floor.
    """


@dataclass(eq=False)
class Kitchen(Room): ...


@dataclass(eq=False)
class Bedroom(Room): ...


@dataclass(eq=False)
class Bathroom(Room): ...


@dataclass(eq=False)
class LivingRoom(Room): ...


@dataclass(eq=False)
class Level(HasRootRegion):
    """
    A level of a building
    """

    @property
    def floor_plane(self) -> Tuple[Point3, Point3]:
        """
        The floor plane of a level, expressed as two points

        :return: The floor plane of the level
        """
        min_point_global = self._world.transform(
            self.root.area.min_point, self._world.root
        )
        max_point_global = self._world.transform(
            self.root.area.max_point, self._world.root
        )
        min_z = min_point_global.z
        return min_point_global, Point3(
            max_point_global.x,
            max_point_global.y,
            min_z,
            reference_frame=self._world.root,
        )


@dataclass(eq=False)
class GroundFloor(Level): ...


@dataclass(eq=False)
class FirstFloor(Level): ...


@dataclass(eq=False)
class SecondFloor(Level): ...


@dataclass(eq=False)
class Wall(HasApertures):
    """
    A wall is a physical entity that separates two spaces and can contain apertures.

    Doors are a computed property.
    """

    @property
    def doors(self) -> Iterable[Door]:
        return [
            door
            for door in self._world.get_semantic_annotations_by_type(Door)
            if door.entry_way and InsideOf(door.entry_way.root, self.root)() > 0.1
        ]

    @classmethod
    def _create_wall_event(cls, scale: Scale) -> SimpleEvent:
        """
        Return the collision shapes for the wall.

        A wall event is created based on the scale of the wall, and doors are removed
        from the wall event. The resulting bounding box collection is converted to
        shapes.
        """
        x_interval = closed(-scale.x / 2, scale.x / 2)
        y_interval = closed(-scale.y / 2, scale.y / 2)
        z_interval = closed(0, scale.z)

        return SimpleEvent.from_data(
            {
                SpatialVariables.x.value: x_interval,
                SpatialVariables.y.value: y_interval,
                SpatialVariables.z.value: z_interval,
            }
        )

    @classmethod
    def get_default_root_kinematic_structure_entity_specification(
        cls,
        name: Optional[str] = None,
        scale: Optional[Scale] = None,
        connection_specification: Optional[ConnectionSpecification] = None,
    ) -> BodySpecification:
        """
        Build the default wall body specification, matching the geometry generated by
        :meth:`create_with_new_body_in_world` (a box whose z runs ``0..scale.z``).

        :param name: The name of bodies created from the specification.
        :param scale: The scale of the wall. ``scale.x`` must be the smallest dimension.
            Defaults to ``Scale()``.
        :param connection_specification: Connection attaching the entity to its parent.
            ``None`` defers to the annotation type's default at spawn time.
        :return: A body specification with the wall box geometry.
        """
        scale = scale or Scale()
        if not (scale.x < scale.y and scale.x < scale.z):
            raise InvalidPlaneDimensions(scale, clazz=Wall)
        return BodySpecification.from_event(
            name,
            cls._create_wall_event(scale).as_composite_set(),
            connection_specification=connection_specification,
        )

    def bloated_bounding_box_collection(
        self,
        origin: HomogeneousTransformationMatrix,
        bloat_amount: float,
        obstacle_height_clearance: float = 0.01,
    ) -> BoundingBoxCollection[VolumetricBoundingBox]:
        """
        Bloat this wall's bounding boxes along their thinner dimension only -- the
        side that faces the room -- rather than symmetrically in x and y.

        :param origin: The origin to express the bounding boxes relative to.
        :param bloat_amount: The amount to bloat by.
        :param obstacle_height_clearance: The amount to bloat by in z, regardless of
            ``bloat_amount``.
        :return: The bloated bounding boxes.
        """
        return BoundingBoxCollection(
            [
                (
                    bounding_box.bloat(bloat_amount, 0, obstacle_height_clearance)
                    if bounding_box.width > bounding_box.depth
                    else bounding_box.bloat(0, bloat_amount, obstacle_height_clearance)
                )
                for bounding_box in self.as_bounding_box_collection_at_origin(origin)
            ],
            origin.reference_frame,
        )


@dataclass(eq=False)
class Bottle(HasRootBody):
    """
    Abstract class for bottles.
    """


@dataclass(eq=False)
class Statue(HasRootBody): ...


@dataclass(eq=False)
class SoapBottle(Bottle):
    """
    A soap bottle.
    """


@dataclass(eq=False)
class WineBottle(Bottle):
    """
    A wine bottle.
    """


@dataclass(eq=False)
class MustardBottle(Bottle):
    """
    A mustard bottle.
    """


@dataclass(eq=False)
class DrinkingContainer(HasRootBody): ...


@dataclass(eq=False)
class Cup(DrinkingContainer, IsPerceivable):
    """
    A cup.
    """


@dataclass(eq=False)
class Mug(DrinkingContainer):
    """
    A mug.
    """


@dataclass(eq=False)
class CookingContainer(HasRootBody): ...


@dataclass(eq=False)
class Lid(HasRootBody): ...


@dataclass(eq=False)
class Pan(CookingContainer):
    """
    A pan.
    """


@dataclass(eq=False)
class PanLid(Lid):
    """
    A pan lid.
    """


@dataclass(eq=False)
class Pot(CookingContainer):
    """
    A pot.
    """


@dataclass(eq=False)
class PotLid(Lid):
    """
    A pot lid.
    """


@dataclass(eq=False)
class Plate(HasSupportingSurface):
    """
    A plate.
    """


@dataclass(eq=False)
class Bowl(HasSupportingSurface, IsPerceivable):
    """
    A bowl.
    """


# Food Items
@dataclass(eq=False)
class Food(HasRootBody):
    """
    A Group class for Food.
    """


@dataclass(eq=False)
class TunaCan(Food):
    """
    A tuna can.
    """


@dataclass(eq=False)
class Bread(Food):
    """
    Bread.
    """

    _synonyms = {
        "bumpybread",
        "whitebread",
        "loafbread",
        "honeybread",
        "grainbread",
    }


@dataclass(eq=False)
class CheezeIt(Food, IsPerceivable):
    """
    Some type of cracker.
    """


@dataclass(eq=False)
class Pringles(Food):
    """
    Pringles chips.
    """


@dataclass(eq=False)
class GelatinBox(Food):
    """
    Gelatin box.
    """


@dataclass(eq=False)
class TomatoSoup(Food):
    """
    Tomato soup.
    """


@dataclass(eq=False)
class Candy(Food, IsPerceivable):
    """
    A candy.
    """

    ...


@dataclass(eq=False)
class Noodles(Food, IsPerceivable):
    """
    A container of noodles.
    """

    ...


@dataclass(eq=False)
class Cereal(Food, IsPerceivable):
    """
    A container of cereal.
    """

    ...


@dataclass(eq=False)
class Milk(Food, IsPerceivable):
    """
    A container of milk.
    """


@dataclass(eq=False)
class SaltContainer(HasRootBody, IsPerceivable):
    """
    A container of salt.
    """


@dataclass(eq=False)
class Produce(Food):
    """
    In American English, produce generally refers to fresh fruits and vegetables
    intended to be eaten by humans.
    """

    pass


@dataclass(eq=False)
class Fruit(Produce):
    """
    Fruit.
    """


@dataclass(eq=False)
class Vegetable(Produce):
    """
    Vegetable.
    """


@dataclass(eq=False)
class Tomato(Fruit):
    """
    A tomato.
    """


@dataclass(eq=False)
class Lettuce(Vegetable):
    """
    Lettuce.
    """


@dataclass(eq=False)
class Carrot(Vegetable):
    """
    A carrot.
    """


@dataclass(eq=False)
class Apple(Fruit):
    """
    An apple.
    """


@dataclass(eq=False)
class Banana(Fruit):
    """
    A banana.
    """


@dataclass(eq=False)
class Orange(Fruit):
    """
    An orange.
    """


@dataclass(eq=False)
class Salt(Food):
    """
    A pack or container of salt (e.g., salt shaker or salt can).
    """


@dataclass(eq=False)
class CoffeeTable(Table):
    """
    A coffee table.
    """


@dataclass(eq=False)
class DiningTable(Table, HasLegs):
    """
    A dining table.
    """


@dataclass(eq=False)
class SideTable(Table):
    """
    A side table.
    """


@dataclass(eq=False)
class Desk(Table, HasLegs):
    """
    A desk.
    """


@dataclass(eq=False)
class Chair(Furniture):
    """
    Abstract class for chairs.
    """


@dataclass(eq=False)
class OfficeChair(Chair):
    """
    An office chair.
    """


@dataclass(eq=False)
class Armchair(Chair):
    """
    An armchair.
    """


@dataclass(eq=False)
class TrashCan(HasCaseAsRootBody, Furniture):
    """
    Abstract class for Trash Can.
    """

    @classproperty
    def hole_direction(self) -> Vector3:
        return Vector3.Z()


@dataclass(eq=False)
class Shelf(Cabinet, HasShelfLayers):
    """
    A shelving unit whose storage surfaces are modelled as explicit shelf layers.

    Each layer is a separate :class:`ShelfLayer` annotation, so objects can be placed on
    and reasoned about per layer.
    """


@dataclass(eq=False)
class Bed(Furniture):
    """
    A bed.
    """


@dataclass(eq=False)
class Sofa(Furniture, HasSupportingSurface):
    """
    A sofa.
    """


@dataclass(eq=False)
class Sink(HasRootBody):
    """
    A sink.
    """


@dataclass(eq=False)
class Kettle(CookingContainer): ...


@dataclass(eq=False)
class Decor(HasRootBody): ...


@dataclass(eq=False)
class WallDecor(Decor):
    """
    Wall decorations.
    """


@dataclass(eq=False)
class Cloth(HasRootBody): ...


@dataclass(eq=False)
class Poster(WallDecor):
    """
    A poster.
    """


@dataclass(eq=False)
class WallPanel(HasRootBody):
    """
    A wall panel.
    """


@dataclass(eq=False)
class Potato(Vegetable): ...


@dataclass(eq=False)
class GarbageBin(HasRootBody):
    """
    A garbage bin.
    """


@dataclass(eq=False)
class Drone(HasRootBody): ...


@dataclass(eq=False)
class ProcthorBox(HasRootBody): ...


@dataclass(eq=False)
class Houseplant(HasRootBody):
    """
    A houseplant.
    """


@dataclass(eq=False)
class SprayBottle(HasRootBody):
    """
    A spray bottle.
    """


@dataclass(eq=False)
class Vase(HasRootBody):
    """
    A vase.
    """


@dataclass(eq=False)
class Book(HasRootBody):
    """
    A book.
    """

    book_front: Optional[BookFront] = None


@dataclass(eq=False)
class BookFront(HasRootBody): ...


@dataclass(eq=False)
class SaltPepperShaker(HasRootBody):
    """
    A salt and pepper shaker.
    """


@dataclass(eq=False)
class Cuttlery(HasRootBody): ...


@dataclass(eq=False)
class Fork(Cuttlery):
    """
    A fork.
    """


@dataclass(eq=False)
class Knife(Cuttlery):
    """
    A butter knife.
    """


@dataclass(eq=False)
class Spoon(Cuttlery, IsPerceivable): ...


@dataclass(eq=False)
class Pencil(HasRootBody):
    """
    A pencil.
    """


@dataclass(eq=False)
class Pen(HasRootBody):
    """
    A pen.
    """


@dataclass(eq=False)
class Baseball(HasRootBody):
    """
    A baseball.
    """


@dataclass(eq=False)
class BottleCap(HasMechanicalJoint):
    """
    A cap that closes a bottle, typically mounted on a screw joint.
    """


@dataclass(eq=False)
class Agent(HasRootBody):
    """
    Represents an entity in the world that can act, move, or be controlled.

    Agents are dynamic bodies with semantic meaning — they may have intent, behavior, or
    be controlled by external or internal logic. Examples include robots, humans, or
    other autonomous actors.
    """


@dataclass(eq=False)
class Human(Agent):
    """
    Represents a human agent in the environment.

    A Person is an Agent that is not robotically actuated and does not provide kinematic
    chains, end_effectors, or robot-specific components.

    This class exists primarily for semantic distinction, so that algorithms can treat
    human agents differently from robots if needed.
    """


@dataclass(eq=False)
class SemanticEnvironmentAnnotation(HasRootBody):
    """
    Represents a semantic annotation of the environment.
    """

    def obstacle_entities(
        self, search_space: BoundingBoxCollection[VolumetricBoundingBox]
    ) -> List[Body]:
        """
        Collect the obstacle bodies to consider within ``search_space``.

        Filters out robot bodies so a robot does not treat itself as an obstacle, and
        bodies without meaningful collision geometry.

        :param search_space: The search space; its reference frame is used to look up
            the owning world.
        :return: The obstacle bodies to consider.
        """
        world = search_space.reference_frame._world
        return [
            body
            for body in self.bodies_with_collision
            if body not in world.robot_bodies_with_collision
        ]

    def build_bloated_obstacle_collection(
        self,
        search_space: BoundingBoxCollection[VolumetricBoundingBox],
        semantic_wall_annotation: Optional[Wall] = None,
        bloat_obstacles: float = 0.0,
        bloat_walls: float = 0.0,
        obstacle_height_clearance: float = 0.01,
    ) -> BoundingBoxCollection[VolumetricBoundingBox]:
        """
        Collect and bloat this annotation's obstacle bounding boxes.

        Applies independent bloat amounts to obstacles and walls.

        :param search_space: The search space; its reference frame is used as the
            origin.
        :param semantic_wall_annotation: An optional wall annotation, bloated by its
            own rule (see :meth:`Wall.bloated_bounding_box_collection`).
        :param bloat_obstacles: Amount to expand each obstacle bounding box
            symmetrically in x and y.
        :param bloat_walls: Amount to expand wall bounding boxes in their thinner
            dimension.
        :param obstacle_height_clearance: Amount to expand every obstacle bounding box
            in z, regardless of ``bloat_obstacles``/``bloat_walls``.
        :return: A collection of the bloated obstacle and wall bounding boxes.
        """
        world_root = search_space.reference_frame
        origin = HomogeneousTransformationMatrix(reference_frame=world_root)

        entities_to_consider = self.obstacle_entities(search_space)

        collections = (
            entity.collision.as_bounding_box_collection_at_origin(origin)
            for entity in entities_to_consider
        )
        obstacle_bounding_boxes = BoundingBoxCollection.merge_all(
            collections, world_root
        )

        bloated_obstacles = BoundingBoxCollection(
            [
                bounding_box.bloat(
                    bloat_obstacles, bloat_obstacles, obstacle_height_clearance
                )
                for bounding_box in obstacle_bounding_boxes
            ],
            world_root,
        )

        if semantic_wall_annotation is not None:
            bloated_obstacles = bloated_obstacles.merge(
                semantic_wall_annotation.bloated_bounding_box_collection(
                    origin, bloat_walls, obstacle_height_clearance
                )
            )

        return bloated_obstacles


@dataclass(eq=False)
class RoomWithWallsAndDoors(Room):
    """
    A room with a type description (e.g., Ktichen) and walls and doors.
    """

    room_type: Optional[str] = field(kw_only=True, default=None)
    """
    Description of the type of the room in natural language.
    """

    walls: List[Wall] = field(kw_only=True, default_factory=list)
    """
    The walls enclosing this room.
    """

    doors: List[Door] = field(kw_only=True, default_factory=list)
    """
    The doors of the room.
    """


@dataclass(eq=False)
class DoorWithType(Door):
    """
    A Door that has a type description, e.g. "main entrance".
    """

    type_description: Optional[str] = field(kw_only=True, default=None)


@dataclass(eq=False)
class Leg(HasRootBody):
    """
    A leg that supports a piece of furniture.
    """


@dataclass(eq=False)
class Cooktop(HasRootBody):
    """
    A cooktop surface for cooking.
    """


@dataclass(eq=False)
class Tool(HasRootBody, ABC):
    """
    A tool that is held by a robot's end effector to act on other bodies.
    """

    def _end_effector_name(self) -> PrefixedName:
        """
        :return: The name of the body that acts as the tool's tip, derived from the
            tool's root name.
        """
        root_name = self.root.name
        return PrefixedName(f"{root_name.name}_end_effector", root_name.prefix)

    def _find_end_effector_body(self) -> Optional[Body]:
        if self.root._world is None:
            return None

        end_effector_name = self._end_effector_name()
        for body in self.root._world.bodies:
            if (
                body.name == end_effector_name
                or body.name.name == end_effector_name.name
            ):
                return body
        return None

    def get_tool_frame(self) -> Body:
        """
        :return: The body acting as the tool's tip, or the tool's root if no dedicated
            tip body exists.
        """
        end_effector = self._find_end_effector_body()
        if end_effector is None:
            return self.root
        return end_effector

    @abstractmethod
    def tool_alignment(self, target: Union[Body, Pose]) -> List[AlignmentPair]:
        """
        :param target: The body or pose the tool acts on.
        :return: The normal pairs that must stay aligned while the tool acts on the
            target.
        """


@dataclass(eq=False)
class ToolWithHandle(Tool, HasHandle, ABC):
    """
    A tool held by its handle, acting through a tip body located ahead of its root.

    If the tip body does not exist yet, it is created and rigidly connected to the
    tool's root.
    """

    def __post_init__(self):
        super().__post_init__()
        if self.root._world is None:
            return
        if self._find_end_effector_body() is not None:
            return
        self._create_end_effector_body()

    def _create_end_effector_body(self):
        world = self.root._world
        tip_body = Body(name=self._end_effector_name())
        with world.modify_world():
            world.add_kinematic_structure_entity(tip_body)
            world.add_connection(
                FixedConnection(
                    parent=self.root,
                    child=tip_body,
                    parent_T_connection_expression=HomogeneousTransformationMatrix.from_xyz_rpy(
                        x=0.1,
                        y=0.0,
                        z=0.0,
                        reference_frame=self.root,
                    ),
                )
            )


@dataclass(eq=False)
class Whisk(ToolWithHandle):
    """
    A whisk for mixing the contents of containers.
    """

    def tool_alignment(self, target: Union[Body, Pose]) -> List[AlignmentPair]:
        return [
            AlignmentPair(
                tip_normal=Vector3(-1, 0, 0, reference_frame=self.root),
                goal_normal=Vector3(0, 0, 1, reference_frame=target),
            )
        ]


@dataclass(eq=False)
class CuttingKnife(ToolWithHandle):
    """
    A knife for cutting food objects.
    """

    def tool_alignment(self, target: Union[Body, Pose]) -> List[AlignmentPair]:
        return [
            AlignmentPair(
                tip_normal=Vector3(1, 0, 0, reference_frame=self.root),
                goal_normal=Vector3(0, 1, 0, reference_frame=target),
            ),
            AlignmentPair(
                tip_normal=Vector3(0, 0, 1, reference_frame=self.root),
                goal_normal=Vector3(0, 0, 1, reference_frame=target),
            ),
        ]


@dataclass(eq=False)
class PouringCup(Tool):
    """
    A cup for pouring liquids into containers.
    """

    def tool_alignment(self, target: Union[Body, Pose]) -> List[AlignmentPair]:
        return [
            AlignmentPair(
                tip_normal=Vector3(0, 0, 1, reference_frame=self.root),
                goal_normal=Vector3(0, 0, 1, reference_frame=target),
            )
        ]


@dataclass(eq=False)
class Sponge(Tool):
    """
    A sponge for wiping surfaces.

    .. note:: The sponge is grasped so its local Z axis points away from the gripper,
        which is why its alignments use negative Z normals unlike the other tools.
    """

    def tool_alignment(self, target: Union[Body, Pose]) -> List[AlignmentPair]:
        if isinstance(target, Body):
            return [
                AlignmentPair(
                    tip_normal=Vector3(0, 0, 1, reference_frame=self.root),
                    goal_normal=Vector3(0, 0, -1, reference_frame=target),
                )
            ]
        return [
            AlignmentPair(
                tip_normal=Vector3(0, 0, -1, reference_frame=self.root),
                goal_normal=self._pose_surface_normal(target),
            )
        ]

    def _pose_surface_normal(self, pose: Pose) -> Vector3:
        """
        :param pose: The pose whose surface normal is computed.
        :return: The pose's local Z axis expressed in the pose's reference frame.
        """
        reference_frame = (
            pose.reference_frame if pose.reference_frame is not None else self.root
        )
        rotation = pose.to_rotation_matrix().to_np()[:3, :3]
        return Vector3.from_iterable(
            rotation @ np.array([0.0, 0.0, 1.0]),
            reference_frame=reference_frame,
        )


@dataclass(eq=False)
class Microwave(IsStorageSpace, HasDoors):
    """
    A microwave oven, a kitchen appliance with a door that heats food placed inside it
    using microwave radiation.
    """


@dataclass(eq=False)
class Hood(HasRootBody):
    """
    A range hood mounted above a cooktop that vents cooking fumes.
    """


@dataclass(eq=False)
class Toaster(HasRootBody):
    """
    A countertop appliance for toasting slices of bread.
    """


@dataclass(eq=False)
class CoffeeMachine(HasRootBody):
    """
    A countertop appliance that brews coffee.
    """
