"""Alembic migration environment for semantic_digital_twin.

Targets the SQLAlchemy metadata generated by ORMatic so that schema changes
produced by re-running the ORM generator can be diffed against a live database
and turned into versioned migration scripts automatically.
"""
from __future__ import annotations

import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from alembic import context

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Allow overriding the database URL via environment variable.
db_url = os.environ.get("SDT_DB_URL")
if db_url:
    config.set_main_option("sqlalchemy.url", db_url)

# Import the generated Base so Alembic can diff against its metadata.
# This import must happen after the ORM generator has been run.
from semantic_digital_twin.orm.ormatic_interface import Base  # noqa: E402

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations without a live database connection (emit SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
